# name: household_inventory_app
name: kcbox1

description: 스마트한 AI 기반 가정용 인벤토리 관리 앱
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  image_picker: ^1.0.4
  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.2.1
  google_mlkit_text_recognition: ^0.11.0
  mobile_scanner: ^3.4.1
  shared_preferences: ^2.0.15
  http: ^0.13.5
  logger: ^2.0.2+1
  flutter_local_notifications: ^15.1.1
  android_alarm_manager_plus: ^3.0.3
  workmanager: ^0.5.1
  flutter_tts: ^3.6.3
  speech_to_text: ^7.0.0
  url_launcher: ^6.2.2

  # ✅ `intl` 패키지는 앱 실행에 필요하므로 여기에 있어야 합니다.
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/data/ai_models/
    - assets/data/labels/
    - assets/data/
    - assets/l10n/

#  fonts:
#    - family: CustomFont
#      fonts:
#fluter        - asset: assets/fonts/custom_font.ttf

